import type { ReviewAnnotation, ReviewSummary } from './review-types';
import type { ReviewComment } from '../../git/platform/platform-client';

export function formatAnnotationsAsComments(annotations: ReviewAnnotation[]): ReviewComment[] {
  return annotations.map(a => ({
    path: a.filePath,
    line: a.startLine,
    body: `**[${a.severity.toUpperCase()}]** ${a.category}: ${a.message}${a.suggestedFix ? '\n\nSuggested fix:\n```\n' + a.suggestedFix + '\n```' : ''}`,
  }));
}

export function formatReviewBody(summary: ReviewSummary): string {
  const lines: string[] = [];
  lines.push('## AI Code Review');
  lines.push('');
  lines.push(`**Overall:** ${summary.summary}`);
  lines.push('');
  if (summary.critical > 0) {
    lines.push(`- ${summary.critical} critical issue(s)`);
  }
  if (summary.warnings > 0) {
    lines.push(`- ${summary.warnings} warning(s)`);
  }
  if (summary.suggestions > 0) {
    lines.push(`- ${summary.suggestions} suggestion(s)`);
  }
  if (summary.praise > 0) {
    lines.push(`- ${summary.praise} positive(s)`);
  }
  lines.push('');
  lines.push('---');
  lines.push('*Generated by Hone AI Review*');
  return lines.join('\n');
}

export function shouldBlockMerge(summary: ReviewSummary): boolean {
  return summary.critical > 0;
}
